[build]
  command = "npm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "20"
  NITRO_PRESET = "netlify"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
